---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 12.5.1 # 11.18.12

provisioner:
  name: chef_zero
  attributes:
    apt:
      compile_time_update: true

platforms:
- name: ubuntu-14.04
- name: ubuntu-12.04
<% if ENV['CI'] %>
- name: centos-7
<% else %>
- name: centos-7.0
<% end %>
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
- name: centos-6.7
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
- name: debian-8.0

suites:
- name: varnish3
  excludes:
    - centos-7.0
    - centos-7
    - debian-8.0
  run_list:
  - recipe[varnish]
  attributes:
    varnish:
      version: '3.0'
- name: varnish4
  run_list:
  - recipe[varnish]
  attributes:
    varnish:
      version: '4.0'
      log_daemon: false
- name: varnish41
  run_list:
  - recipe[varnish]
  attributes:
    varnish:
      version: '4.1'
      log_daemon: false

- name: distro_libraries
  includes:
    - ubuntu-14.04
    - centos-7.0
    - centos-6.7
    - debian-8.0
  run_list:
    - recipe[install_varnish::distro_install]

- name: vendor_libraries
  includes:
    - ubuntu-14.04
    - centos-7.0
    - centos-6.7
    - debian-8.0
  run_list:
    - recipe[install_varnish::vendor_install]

- name: vendor_41_libraries
  includes:
    - ubuntu-14.04
    - centos-7.0
    - centos-6.7
  run_list:
    - recipe[install_varnish::vendor_41_install]

- name: libraries_defaults
  includes:
    - ubuntu-14.04
    - centos-7.0
    - centos-6.7
    - debian-8.0
  run_list:
    - recipe[install_varnish::default_settings]
