driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: 12.22.5

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: true

platforms:
- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts net-tools wget

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install yum which systemd-sysv initscripts wget net-tools

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools iproute2 -y

- name: opensuse-leap
  driver:
    image: opensuse:leap
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which hostname

# Unless other wise noted excludes exist because the distro version get's installed instead (need pinning to support this)
suites:
- name: varnish3
  excludes:
    - ubuntu-16.04
    - debian-8
    - fedora-latest
    - opensuse-leap
  run_list:
    - recipe[install_varnish::test_reqs]
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 3.0
- name: varnish4
  excludes:
    - fedora-latest
    - opensuse-leap
  run_list:
    - recipe[install_varnish::test_reqs]
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 4.0
- name: varnish41
  excludes:
    - fedora-latest
    - opensuse-leap
  run_list:
    - recipe[install_varnish::test_reqs]
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 4.1
- name: varnish5
  excludes:
    - opensuse-leap
  run_list:
    - recipe[install_varnish::test_reqs]
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 5
- name: varnish6
  run_list:
    - recipe[install_varnish::test_reqs]
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 6.0
- name: distro
  excludes:
    - centos-6 # Uses varnish 2 which we don't support
    - opensuse-leap
  run_list:
    - recipe[install_varnish::test_reqs]
    - recipe[install_varnish::distro_install]
  attributes:
    varnish:
      configure:
        repo:
          action: :nothing
- name: full_stack
  run_list:
    - recipe[install_varnish::test_reqs]
    - recipe[install_varnish::full_stack]
  excludes:
    - centos-6 # Full stack tests use distro install so need to skip centos-6 for now.
    - opensuse-leap
  attributes:
    varnish:
      configure:
        repo:
          action: :nothing
