---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    apt:
      compile_time_update: true
    varnish:
      backend_host: '127.0.0.10'

platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-7.3
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]
- name: centos-6.8
  run_list:
    - recipe[disable_ipv6::disable_ipv6]
    - recipe[yum-epel]

# Excludes exist because the distro version get's installed instead (need pinning to for this to work otherwise)
suites:
- name: varnish3
  excludes:
    - centos-7.3
    - ubuntu-16.04
  run_list:
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 3.0
- name: varnish4
  excludes:
    - ubuntu-16.04
  run_list:
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 4.0
- name: varnish41
  run_list:
    - recipe[install_varnish::vendor_install]
  attributes:
    varnish:
      major_version: 4.1
- name: distro
  run_list:
    - recipe[install_varnish::distro_install]
- name: full_stack
  run_list:
    - recipe[install_varnish::full_stack]
