sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE=varnish3-ubuntu-1404
    - INSTANCE=varnish3-centos-6
    - INSTANCE=varnish3-centos-7
    - INSTANCE=varnish4-ubuntu-1404
    - INSTANCE=varnish4-ubuntu-1604
    - INSTANCE=varnish4-centos-6
    - INSTANCE=varnish4-centos-7
    - INSTANCE=varnish41-ubuntu-1404
    - INSTANCE=varnish41-ubuntu-1604
    - INSTANCE=varnish41-centos-7
    - INSTANCE=varnish41-centos-6
    - INSTANCE=varnish5-ubuntu-1404
    - INSTANCE=varnish5-ubuntu-1604
    - INSTANCE=varnish5-centos-7
    - INSTANCE=varnish5-centos-6
    - INSTANCE=varnish6-ubuntu-1604
    - INSTANCE=varnish6-centos-7
    - INSTANCE=distro-ubuntu-1404
    - INSTANCE=distro-ubuntu-1604
    - INSTANCE=distro-centos-7
    - INSTANCE=full-stack-ubuntu-1404
    - INSTANCE=full-stack-ubuntu-1604
    - INSTANCE=full-stack-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
