---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: varnish3-debian-8
          suite: varnish3-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish3-debian-9
          suite: varnish3-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish3-centos-6
          suite: varnish3-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish3-centos-7
          suite: varnish3-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish3-fedora-latest
          suite: varnish3-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish3-ubuntu-1804
          suite: varnish3-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish3-opensuse-leap
          suite: varnish3-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-debian-8
          suite: varnish4-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-debian-9
          suite: varnish4-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-centos-6
          suite: varnish4-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-centos-7
          suite: varnish4-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-fedora-latest
          suite: varnish4-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-ubuntu-1604
          suite: varnish4-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-ubuntu-1804
          suite: varnish4-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish4-opensuse-leap
          suite: varnish4-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-debian-8
          suite: varnish41-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-debian-9
          suite: varnish41-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-centos-6
          suite: varnish41-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-centos-7
          suite: varnish41-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-fedora-latest
          suite: varnish41-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-ubuntu-1604
          suite: varnish41-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-ubuntu-1804
          suite: varnish41-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish41-opensuse-leap
          suite: varnish41-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-debian-8
          suite: varnish5-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-debian-9
          suite: varnish5-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-centos-6
          suite: varnish5-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-centos-7
          suite: varnish5-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-fedora-latest
          suite: varnish5-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-ubuntu-1604
          suite: varnish5-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-ubuntu-1804
          suite: varnish5-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish5-opensuse-leap
          suite: varnish5-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-debian-8
          suite: varnish51-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-debian-9
          suite: varnish51-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-centos-6
          suite: varnish51-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-centos-7
          suite: varnish51-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-fedora-latest
          suite: varnish51-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-ubuntu-1604
          suite: varnish51-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-ubuntu-1804
          suite: varnish51-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish51-opensuse-leap
          suite: varnish51-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-debian-8
          suite: varnish52-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-debian-9
          suite: varnish52-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-centos-6
          suite: varnish52-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-centos-7
          suite: varnish52-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-fedora-latest
          suite: varnish52-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-ubuntu-1604
          suite: varnish52-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-ubuntu-1804
          suite: varnish52-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish52-opensuse-leap
          suite: varnish52-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-debian-8
          suite: varnish60-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-debian-9
          suite: varnish60-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-centos-7
          suite: varnish60-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-fedora-latest
          suite: varnish60-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-ubuntu-1604
          suite: varnish60-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-ubuntu-1804
          suite: varnish60-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish60-opensuse-leap
          suite: varnish60-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-debian-8
          suite: varnish61-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-debian-9
          suite: varnish61-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-centos-7
          suite: varnish61-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-fedora-latest
          suite: varnish61-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-ubuntu-1604
          suite: varnish61-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-ubuntu-1804
          suite: varnish61-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: varnish61-opensuse-leap
          suite: varnish61-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-debian-8
          suite: distro-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-debian-9
          suite: distro-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-centos-7
          suite: distro-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-fedora-latest
          suite: distro-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-ubuntu-1604
          suite: distro-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-ubuntu-1804
          suite: distro-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: distro-opensuse-leap
          suite: distro-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-debian-8
          suite: full-stack-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-debian-9
          suite: full-stack-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-centos-7
          suite: full-stack-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-fedora-latest
          suite: full-stack-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-ubuntu-1604
          suite: full-stack-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-ubuntu-1804
          suite: full-stack-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: full-stack-opensuse-leap
          suite: full-stack-opensuse-leap
          requires: *lint_and_unit
